### PR TITLE
Do not show drag buttons on elements that are only children

### PR DESCRIPTION
**Pull request by cibernox**
Since dragging elements is for sorting elements among its siblings, this button should not be seen on only children.

One possible are of confusion for this is when an element, like an `<strong>`, is placed in the middle of Text nodes that aren't wrapped in any tag. In that situation dragging isn't allowed either because unlike with DOM elements, there's no good way of telling where we want that element to land (in between any two characters?)

### CODE REVIEW

**Review by leandrocp — CHANGES_REQUESTED** [review]
Hey @cibernox I noticed a small bug after moving elements with no children. Seems like it loses track of the selected element.

See the attached video:


https://github.com/user-attachments/assets/882c68da-112a-43fc-a95e-74b4eaafd84e

**Comment by cibernox** [comment]
@leandrocp I believe that bug existed before and should have been fixed by https://github.com/BeaconCMS/beacon_live_admin/pull/214

**Comment by cibernox** [comment]
Either way, I don't think it's related to this PR.

**Comment by leandrocp** [comment]
> @leandrocp I believe that bug existed before and should have been fixed by #214

I don't see the bug on the main branch, so it seems to be something new. Forcing `canBeDragged` to `true` makes the error go away as well 🤔

**Comment by cibernox** [comment]
I added a few null-checks. At some point `$selectedDomElement.parentElement.children` must be null and it's failing, although the way it's manifesting is unexpected. Try again.

**Comment by leandrocp** [comment]
Yeah I found the same issue on https://github.com/BeaconCMS/beacon_live_admin/pull/218 with assets updated. Let me try this PR again.

**Comment by leandrocp** [comment]
Working now!

**Pull request merged**
