### PR TITLE
Pages: Sorting and Pagination

### PR DESCRIPTION
**Pull request by ChristianTovar**
## Description

- [x] Sort by title, path
- [x] Paginate by page, 20 records by page
- [x] Use query params to preserve state as ?query=FOO&page=INT&sort=NAME
- [ ] Searching should reset pagination to page 1 and preserve sort query param and current state
- [x] Paginating should preserve search query and sort params and their current state
- [x] Navigation component

## Issue
This PR tackles https://github.com/BeaconCMS/beacon_live_admin/issues/87

## Screenshots

image

## Pagination Component Demo

https://github.com/BeaconCMS/beacon_live_admin/assets/13787741/86c39717-ae75-4615-a4d4-8a7ac5c556b8

### CODE REVIEW

**Comment by leandrocp** [comment]
Hey @ChristianTovar it's looking good. Just found a small bug.

When there are no pages, it displays the following:

Screenshot 2024-01-19 at 1 34 13 PM

Clicking on the `0` crashes with:

```elixir
%Postgrex.Error{message: nil, postgres: %{code: :invalid_row_count_in_result_offset_clause, line: "374", message: "OFFSET must not be negative", ...}
```

**Comment by ChristianTovar** [comment]
@leandrocp I've fixed the error for when there are no pages at all, we won't render the pagination component nor the upper sorting element. We still have some tests that are complaining about some code that is currently on beacon core for counting pages, how do we use the latest up-to-date beacon core stuff in tests for this particular case?

**Comment by leandrocp** [comment]
> @leandrocp I've fixed the error for when there are no pages at all, we won't render the pagination component nor the upper sorting element.

👍🏻 

> We still have some tests that are complaining about some code that is currently on beacon core for counting pages, how do we use the latest up-to-date beacon core stuff in tests for this particular case?

You can just update the dependency: `mix deps.update beacon` - there's no blockers for doing so, actually beacon_live_admin should keep `beacon` as fresh as possible

**Review by leandrocp — APPROVED** [review]
✅ 
Feel free to merge it thanks!

**Pull request merged**
